In [2]:
import numpy as np

In [ ]:
#Count The Number Of Times Each Value Appears In An Array Of Integers

In [9]:
l = [1,1,2,3,1,2,4,5,6,7,7]
arr1 = np.array(l)
arr1
np.array(np.unique(arr1, return_counts=True)).T

array([[1, 3],
       [2, 2],
       [3, 1],
       [4, 1],
       [5, 1],
       [6, 1],
       [7, 2]], dtype=int64)

In [ ]:
#2. Given 9 Integers. You have to convert them into 3*3 Numpy array using Reshape function.

In [17]:
arr2 = np.arange(1,10)
arr2
arr2  =np.reshape(arr2,(3,3))
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#3. How to find the memory size of any array

In [21]:
print(arr2.nbytes)

36


In [ ]:
#4. Create a 2d array of size 10 by 10 with 1 on the border and 0 inside.

In [25]:
arr4 = np.ones((10,10), dtype = int)
arr4[1:-1,1:-1] = 0
print(arr4)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [ ]:
#5.Create a 8x8 matrix and fill it with a checkerboard pattern.

In [32]:
checkboard = np.zeros((8,8), dtype= int )
checkboard[1::2, 1::2] = 1
checkboard[::2, 1::2] = 1

In [33]:
checkboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [ ]:
#6.Normalize a 5x5 random matrix

In [36]:
random_matrix = np.random.randint(1,100,(5,5))
random_matrix
normalize = (random_matrix  - random_matrix .min())/(random_matrix .std(axis=0))
normalize

array([[ 0.0992225 ,  1.95656778,  2.72117901,  1.85905075, 10.26012692],
       [ 2.81130405,  1.49864766,  0.        ,  2.53215533,  7.94332407],
       [ 1.98444992,  0.41629102,  2.48455475,  2.91678652,  7.50202829],
       [ 0.52918665,  0.20814551,  1.95215016,  0.35257859,  9.37753536],
       [ 0.82685413,  2.91403713,  1.06480918,  0.70515718,  9.15688747]])

In [ ]:
#7. Given a 1D array in range(0,11), negate all elements which are between 3 and 8, in place.

In [45]:
original = np.arange(0,11)
print(original)
negate = np.where((original > 3) & (original < 8))
original[negate] =  original[negate] * (-1)
print(original)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [ ]:
#8. How to get the dates of yesterday, today and tomorrow?

In [51]:
yesterday = np.datetime64('today','D') - np.timedelta64('1', 'D')
print(yesterday)
today = np.datetime64('today', 'D')
print(today)
tomorrow = np.datetime64('today','D') + np.timedelta64('1','D')
print(tomorrow)

2020-02-14
2020-02-15
2020-02-16


In [ ]:
#9.Generate two arrays of size 2X4 & 3X3, find difference between them.

In [56]:
first = np.random.randint(1,25,(2,4))
print(first)
#np.reshape(first,(3,3))
second = np.random.randint(11,50,(3,3))
print(second)
print(first - second)

[[ 7 15 19 20]
 [ 5 12 10 14]]
[[29 31 44]
 [40 39 17]
 [20 38 35]]


ValueError: operands could not be broadcast together with shapes (2,4) (3,3) 

In [ ]:
#10. Given 1d array of ['cat','dog','rat'], genrate 100 elements of 1d array consisting of the above 3 value ?

In [60]:
l = ['cat','dog','rat']
one_array = np.array(l)
print(one_array)



['cat' 'dog' 'rat']


In [ ]:
#11. Given a two dimensional array, how to extract unique rows?

In [80]:
l = [[1,2,3], [1,2,3], [22,33,44]]
a = np.array(l)
print(a)
unique = np.unique(a, axis =0 )
print()
print(unique)

[[ 1  2  3]
 [ 1  2  3]
 [22 33 44]]

[[ 1  2  3]
 [22 33 44]]


In [ ]:
#13. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.

In [ ]:
#14. How to find the closest value (to a given scalar) in a vector?

In [ ]:

#15. Consider a random vector with shape (10,2) representing coordinates, find point by point distances. Use euclidian distance.

In [88]:
random_vector = np.random.randint(1,20,(10,2))
print(random_vector)
x, y = np.atleast_2d(random_vector[:,0],random_vector[:,1])
print(x,y)
euc_dist = np.sqrt(((x -x.T) **2) + ((y - y.T)**2))
print(euc_dist)

[[ 8 16]
 [19 11]
 [16 15]
 [ 8 14]
 [ 9 11]
 [10  2]
 [ 9  1]
 [ 8 10]
 [10  3]
 [ 4  6]]
[[ 8 19 16  8  9 10  9  8 10  4]] [[16 11 15 14 11  2  1 10  3  6]]
[[ 0.         12.08304597  8.06225775  2.          5.09901951 14.14213562
  15.03329638  6.         13.15294644 10.77032961]
 [12.08304597  0.          5.         11.40175425 10.         12.72792206
  14.14213562 11.04536102 12.04159458 15.8113883 ]
 [ 8.06225775  5.          0.          8.06225775  8.06225775 14.31782106
  15.65247584  9.43398113 13.41640786 15.        ]
 [ 2.         11.40175425  8.06225775  0.          3.16227766 12.16552506
  13.03840481  4.         11.18033989  8.94427191]
 [ 5.09901951 10.          8.06225775  3.16227766  0.          9.05538514
  10.          1.41421356  8.06225775  7.07106781]
 [14.14213562 12.72792206 14.31782106 12.16552506  9.05538514  0.
   1.41421356  8.24621125  1.          7.21110255]
 [15.03329638 14.14213562 15.65247584 13.03840481 10.          1.41421356
   0.          9.05538514

In [ ]:
#16.How to sort an array by the nth column?

In [93]:
matrix = np.random.randint(1,20,(3,3))
print(matrix)
n = 2
arr = matrix[matrix[:,n].argsort()]
print()
print(arr)

[[ 9 13 10]
 [ 8 12 14]
 [12  6  9]]

[[12  6  9]
 [ 9 13 10]
 [ 8 12 14]]


In [ ]:
#17.How to tell if a given 2D array has null columns?

In [99]:
arr2
np.isnan(arr2).any()

False

In [ ]:
#18.Considering a two dimensions array, how to get sum over the last two columns at once?

In [103]:
two_d

array([[40,  9],
       [30, 90]])

In [107]:
addition = two_d.reshape(two_d.shape[:-2] + (-1,)).sum(axis=0)
print(addition)

169


In [ ]:
#19. Given a 2d array of 5X5, increment 1st column by 1, second column by 2, 3rd column by 3 & so on till the last column

In [140]:
array = np.random.randint(1,25,(5,5))
print(array)
l = []
for i in range(5):
    for j in range(5):
        array[i][j] += i
        l.append(array[i][j])
l = np.array(l)
l = l.reshape(5,5)
print()
print(l)

[[22  4 21  6 19]
 [ 5 24  7 13 24]
 [23 15 19 11  5]
 [ 5 15 15 15 19]
 [ 3  4  5 16 12]]

[[22  4 21  6 19]
 [ 6 25  8 14 25]
 [25 17 21 13  7]
 [ 8 18 18 18 22]
 [ 7  8  9 20 16]]


In [ ]:
#20.Given a 1d array(size 100) of boolean values, identify total number of True in it.

In [130]:
array = np.ones((10,10), dtype = int)
np.count_nonzero(array)

100

In [ ]:
#21. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?¶

In [ ]:
#22.How to swap two rows of an array?

In [122]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
arr2[[1, 2]] = arr2[[2, 1]]
arr2

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [ ]:
#23.How to get n largest value of an array?

In [ ]:
#24.How to get index of top two highest value in a 1d array?

In [ ]:
#24Given two random arrays of shape 5X5, identify the common elements between them

In [121]:
first_array = np.random.randint(1,20,(5,5))
print(first_array)
second_array = np.random.randint(2,20,(5,5))
print()
print(second_array)
np.intersect1d(first_array, second_array)

[[ 4  4 18  5  4]
 [ 2  5  8  7 16]
 [11 19  9 10  3]
 [12 16  8  6  9]
 [13  3  8  6 18]]

[[ 8  7 17  9  5]
 [ 7 16 14 18  5]
 [18 17 18 12 10]
 [ 9 10 19  8  3]
 [ 3 18 17  7  4]]


array([ 3,  4,  5,  7,  8,  9, 10, 12, 16, 18, 19])

In [ ]:
#25. How to get index of top two highest value in a 1d array?

In [119]:
l = [2,22,11,-11,33,7,13,872,-23]
arr_top = np.array(l)
print(arr_top)
highest = np.argmax(arr_top)
np.argmax()

[  2  22  11 -11  33   7  13 872 -23]


7